### ISSUE TITLE
(Feature) Script to generate list of txs from 

### ISSUE THREAD

**Issue by igorbarinov** [oraclesorg/poa-chain-spec#4]
Problem:
Put presale participants in `chain.json` file is not a good practice:
- the file is harder to read
- longer time to start a node

Solution:
Send txs to pre-sale participants wallets when the network starts from a MoC wallet 
There is a list of accounts and balances structured as a CSV file with two columns.
The first column is ethereum address and the second column is value in POA (not Wei)
```
0x2c57E1E3AD53F0b971422696c1470cEB84F83B1B,6888412
0xca9B0753E2Ea13d7bBE0e90516Bcf940A275eFA8,540773
```

**Comment by rstormsf** [comment]
@igorbarinov Closed in 
https://github.com/oraclesorg/oracles-scripts-owner/pull/1

**Comment by igorbarinov** [comment]
Thanks, used it in ceremony
